services:
  db_auth:
    image: postgres:16-alpine
    container_name: auth_entic_postgres
    restart: always
    # Le decimos a Docker que lea el .env del backend
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - auth_entic_data:/var/lib/postgresql/data

volumes:
  auth_entic_data: